### ISSUE TITLE
No view found for fragment folderfragment

### ISSUE THREAD

**Issue by ArjunPatidar-numero** [Mindinventory/Lassi-Android#53] opened 2022-02-24 15:05 UTC
```
2022-02-24 20:31:03.054 30350-30350/com.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.onlyfriends, PID: 30350
    java.lang.IllegalArgumentException: No view found for id 0x7f0a03cb (com.onlyfriends:id/ftContainer) for fragment FolderFragment{dce2c5a} (eb37522f-bea5-41cf-ba94-79b1cc223c3c id=0x7f0a03cb)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:513)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
        at android.app.Activity.performStart(Activity.java:7923)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3335)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7592)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by sanjay-mi** [comment] 2022-03-01 09:23
Hello @ArjunPatidar-numero 

Thank you for using Lassi library.
It would be great for us if the you can share the below things to understand the root cause of the issue.
 * Library version
 * Code snippet
 * Device specification like (Manufacturer, OS version, etc)
 * Screenshot/video with steps to reproduce the issue

**Comment by sanjay-mi** [comment] 2022-07-21 11:52
For a long time, there is no updates on this issue. 
So, closing it. 
If the issue still exists feel free to create a new issue or ReOpen it.

**Closed by sanjay-mi** 2022-07-21 11:52 UTC
Labels: question
